version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  app_frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
  
  app_backend:
    build: ./backend
    container_name: app_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo_db:27017/itemsdb
    volumes:
      - ./backend:/app
    command: ["node", "index.js"]

volumes:
  mongo_data:
